# Generated by Django 4.0.3 on 2022-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftable',
            name='status',
            field=models.BooleanField(default=0, help_text='0:processing, 1:completed'),
        ),
    ]
