# Generated by Django 4.0.3 on 2022-03-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pdftable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='***', max_length=200)),
                ('type_design', models.CharField(default='***', max_length=200)),
                ('colour', models.CharField(default='***', max_length=200)),
                ('pdftable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdftable', to='app.pdftable')),
            ],
            options={
                'db_table': 'OrderDetails',
            },
        ),
    ]
