# Generated by Django 4.0.3 on 2022-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='***', max_length=200)),
                ('size', models.CharField(default='***', max_length=200)),
            ],
            options={
                'db_table': 'ProductSize',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='***', max_length=200)),
                ('type', models.CharField(default='***', max_length=200)),
            ],
            options={
                'db_table': 'ProductType',
            },
        ),
    ]
