# Generated by Django 4.0.3 on 2022-03-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderdetails_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.BooleanField(default=0, help_text='0:processing, 1:completed'),
        ),
    ]
