# Generated by Django 4.0.3 on 2022-03-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderdetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='***', max_length=200)),
                ('code', models.CharField(default='***', max_length=200)),
                ('type', models.CharField(default='***', max_length=200)),
                ('colour', models.CharField(default='***', max_length=200)),
                ('pdftable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdftable_final', to='app.pdftable')),
            ],
            options={
                'db_table': 'OrderDetailsFinal',
            },
        ),
    ]
