# Generated by Django 4.0.3 on 2022-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderdetailsfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsfinal',
            name='size',
            field=models.CharField(default='***', max_length=200),
        ),
    ]
