# Generated by Django 4.0.3 on 2022-05-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderdetails_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsfinal',
            name='order_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdftabledetails', to='app.orderdetails'),
        ),
    ]
