# Generated by Django 3.2.9 on 2022-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderdetailsfinal_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsfinal',
            name='photo',
            field=models.ImageField(blank=True, default='default', null=True, upload_to=''),
        ),
    ]
