# Generated by Django 3.2.9 on 2022-05-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orderdetailsfinal_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistinctFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='***', max_length=200)),
                ('code', models.CharField(default='***', max_length=200)),
                ('type', models.CharField(default='***', max_length=200)),
                ('size', models.CharField(default='***', max_length=200)),
                ('colour', models.CharField(default='***', max_length=200)),
                ('photo', models.ImageField(blank=True, default='default', null=True, upload_to='')),
                ('distinct_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdistinctfinal', to='app.orderdetailsfinal')),
            ],
            options={
                'db_table': 'DistinctFinal',
            },
        ),
    ]
